### ISSUE TITLE
[Troubleshooting] Doesn't work for specific user

### ISSUE THREAD

**Issue by matheusbsf** [cathyjf/SekiroFpsUnlockDll#4]
I tried all three .dll, game is still locked at 60fps, help

**Comment by cathyjf** [comment]
I can confirm that the framerate unlocking still works correctly for me on the latest version of the game available on Steam. I am unable to help with any other version of the game because the only one I have is the latest version of the game available on Steam.

Also, please make sure that you've placed the DLL in the same directory as the `sekiro.exe` file.

If you are using the latest version of the game available on Steam and if you are sure that you placed the DLL in the correct location, **please reply again** to let me know and I'll ask some follow-up questions to see if I can help you.

**Comment by Klemci** [comment]
NO, VSync in forced ON by default, Fast Sync works.
